### ISSUE TITLE
Submit button left disabled when HTML5 validation is throw

### ISSUE THREAD

**Issue by fxgallego** [TrestleAdmin/trestle#91] opened 2018-03-07 22:02 UTC
When a form field has a required: true or numeric validation, if the user clicks the submit button while some fields are invalid, the submit button is left in a disabled state with the loading indicator.

I've patched this in `trestle/components/_form.js` this way [as this SO answer recommends](https://stackoverflow.com/questions/11866910/how-to-force-a-html5-form-validation-without-submitting-it-via-jquery)
```
javascript
 // Delay to ensure form is still submitted

    setTimeout(function() {
      if(form[0].checkValidity()) {
            button.prop('disabled', true).addClass('loading');
        }
    }, 1);
```

**Comment by spohlenz** [comment] 2018-03-08 10:23
Thank you. This should be fixed in 1fad062.

**Closed by spohlenz** 2018-03-08 10:23 UTC

**Comment by fxgallego** [comment] 2018-03-08 11:26
BTW, do you have plans to add support for mark inputs as required when either a null: false field or presence: true validation exists? Maybe it's done but I haven't found it in the docs or code. Thanks for Trestle, it's wonderfully written.

**Comment by spohlenz** [comment] 2018-03-09 01:39
I don't currently have plans to automate this, mainly because it can only ever catch the simpler cases, and the regular non-HTML5 validations work as intended. However I wouldn't be opposed to making changes (not sure what those would be) that would help make this easier for either a plugin or developer.

**Comment by fxgallego** [comment] 2018-03-12 01:12
BTW, [SimpleForm](https://github.com/plataformatec/simple_form) currently marks required fields with *. I think that's a good default. This is an excerpt from the usage instructions:

>Required fields are marked with an * prepended to their labels.

>By default all inputs are required. When the form object includes ActiveModel::Validations (which, for example, happens with Active Record models), fields are required only when there is presence validation. Otherwise, Simple Form will mark fields as optional. For performance reasons, this detection is skipped on validations that make use of conditional options, such as :if and :unless.
