### ISSUE TITLE
Installing Trestle interferes with Turbo frame

### ISSUE THREAD

**Issue by yangtheman** [TrestleAdmin/trestle#518] opened 2024-10-31 21:53 UTC
Hi there, 

I noticed that on Rails 8.0.0.rc2, installing Trestle (0.10.1) somehow removes or blocks `/cable` route. Normally you would see something like this for a page that has turbo frame: 

```
Started GET "/cable" for ::1 at 2024-10-31 14:34:29 -0700
Started GET "/cable" [WebSocket] for ::1 at 2024-10-31 14:34:29 -0700
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
Turbo::StreamsChannel is transmitting the subscription confirmation
Turbo::StreamsChannel is streaming from conversation
```

But with Trestle, you see the following and none of the turbo works. 

```
ActionController::RoutingError (No route matches [GET] "/cable"):
  
Started GET "/cable" for ::1 at 2024-10-31 14:48:27 -0700
```

This is with nothing else changed except install Trestle and **before** running `bin/rails generate trestle:install `. 

This is only thing that's preventing us from going forward and using Trestle. Any help would be much appreciated.

**Comment by spohlenz** [comment] 2024-11-01 00:37
I have been able to reproduce this on Rails 8.0.0.rc2, though the issue doesn't appear to be present in Rails 7.2. I've narrowed it down to the call to `Rails.application.reload_routes!` within the [Trestle reloader](https://github.com/TrestleAdmin/trestle/blob/main/lib/trestle/reloader.rb#L23), and I believe is related to test failures I'm seeing with [trestle-auth on Rails 8.0](https://github.com/TrestleAdmin/trestle-auth/pull/58).

I will keep investigating further.

**Comment by spohlenz** [comment] 2024-11-04 00:14
It looks like there is now a PR in place for rails code (rails/rails#53522) to fix this. I've tested the branch and it appears to fix this issue as well as the trestle-auth test failures with Rails 8.0.

I'll keep this issue open until it is fully merged in upstream but hopefully that will be the solution here.

**Comment by spohlenz** [comment] 2024-11-05 23:43
Closing as the fix has now been merged into the Rails [8-0-stable](https://github.com/rails/rails/tree/8-0-stable) branch.

**Closed by spohlenz** 2024-11-05 23:43 UTC

**Comment by yangtheman** [comment] 2024-11-07 20:38
@spohlenz Hey, I just want to thank you for being on top of the issue!  I really appreciate it.
